
- name: Create New User
  hosts: all
  become: true
  gather_facts: false
  vars:
# Define your username and password here that you want to create on target hosts.
    username: newuser
  tasks:
    - name: Create User
      ansible.builtin.user:
        name: "{{ username }}"
        state: present
        shell: /usr/bin/bash
        append: yes

    - name: check user
      become: yes
      become_user: alex
      become_method: su
      become_flags: '--login'
      shell: mkdir ~/.ssh; chmod 700 ~/.ssh; cat ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDioaNk5Wp9F3jl/dP47vU2wqnomRSLmB6sBVW5Vv4hw alexgalani@pvh.com >> ~/.ssh/authorized_keys; chmod 600 ~/.ssh/authorized_keys
